function [CoMResTraj, CoMBbTraj, CoMScTraj] = CentOfMassResBbSc(traj, atmGrpRes, atmNam)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% CentOfMassResBbSc produces the trajectory of center of mass(CoM) of amino acid(res),
% backbone(Bb) and side-chain(sc)
% inputs: 
% trajectory of all atoms(traj), 
% 1st columnd: atom types(ATOM=1 or HETATM=2), 2nd column: residue number(atmGrpRes) 
% atoms' name(atmNam) all generated by PdbTrajRead code

% atomic weights 
Nw = 14.01; Cw = 12.01; Ow = 16.00; Sw = 32.60;
weis = [Nw, Cw, Ow, Sw]; 

% initilizing
nFrm = size(traj,1);
frsRes = min(atmGrpRes(:,2));
lstRes = max(atmGrpRes(:,2));
nRes = (lstRes - frsRes) +1;
[CoMResTraj, CoMBbTraj, CoMScTraj] = deal(zeros(nRes,3,nFrm));

traj = permute(traj,[3 2 1]);

% if first residue is not res number 1

for r = frsRes:lstRes
    % selecting the trajectory of each residue
    resTraj = traj(atmGrpRes(:,2)==r,:,:);
    % selecting the atom names of residue
    resAtmNam = atmNam(atmGrpRes(:,2)==r);
    
    % weighting the traj of residue
    resWei = 0;
    %nA = size(resAtmNam,1); % number of atoms in each residue
    for a = 1:size(resAtmNam,1);
        switch resAtmNam{a}(1)
            case 'N'
                resWeiTraj(a,:,:) = resTraj(a,:,:).*weis(1);
                resWei = resWei + weis(1);
            case 'C'
                resWeiTraj(a,:,:) = resTraj(a,:,:).*weis(2);
                resWei = resWei + weis(2);
            case 'O'
                resWeiTraj(a,:,:) = resTraj(a,:,:).*weis(3);
                resWei = resWei + weis(3);
            case 'S'
                resWeiTraj(a,:,:) = resTraj(a,:,:).*weis(4);
                resWei = resWei + weis(4);
        end
    end
    % center of mass for residue
    CoMResTraj(r,1,:) = sum(resWeiTraj(:,1,:),1)./resWei; % X
    CoMResTraj(r,2,:) = sum(resWeiTraj(:,2,:),1)./resWei; % Y
    CoMResTraj(r,3,:) = sum(resWeiTraj(:,3,:),1)./resWei; % Z
    
    % center of mass for BackBone
     bbAtms = ismember(resAtmNam,{'N  ', 'CA ', 'C  ', 'O  '}); % bb atoms
     bbWei = sum(weis(1:3))+weis(2);
    CoMBbTraj(r,1,:) = sum(resWeiTraj(bbAtms,1,:),1)./bbWei; % X
    
    CoMBbTraj(r,2,:) = sum(resWeiTraj(bbAtms,2,:),1)./bbWei; % Y
    
    CoMBbTraj(r,3,:) = sum(resWeiTraj(bbAtms,3,:),1)./bbWei; % Z
    
    % center of mass of SideChain
    CoMScTraj(r,1,:) = sum(resWeiTraj(~bbAtms,1,:),1)./(resWei-bbWei); % X
    
    CoMScTraj(r,2,:) = sum(resWeiTraj(~bbAtms,2,:),1)./(resWei-bbWei); % Y
    
    CoMScTraj(r,3,:) = sum(resWeiTraj(~bbAtms,3,:),1)./(resWei-bbWei); % Z
    clear r resTraj resAtmNam resWei a resWeiTraj bbAtms bbWei 
end